# Generated by Django 4.2.3 on 2023-07-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
