# Generated by Django 4.2.3 on 2023-07-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_board_date_alter_board_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='board',
            new_name='post',
        ),
    ]
