# Generated by Django 4.2.3 on 2023-07-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_rename_board_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='board',
        ),
    ]
