# Generated by Django 4.2.3 on 2023-07-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_rename_post_comment_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='board',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
